Unbreak build on FreeBSD (#188)
* notifications: use glib type of unsigned long after bad121a4d7b8

src/panel/widgets/notifications/notification-info.cpp:54:5: error: unknown type name 'ulong'
    ulong pixel_size = (channels * bits_per_sample + 7) / 8;
    ^
src/panel/widgets/notifications/notification-info.cpp:55:40: error: expected ')'
    if (data_var.get_size() != ((ulong)height - 1) * (ulong)rowstride + (ulong)width * pixel_size)
                                       ^
src/panel/widgets/notifications/notification-info.cpp:55:32: note: to match this '('
    if (data_var.get_size() != ((ulong)height - 1) * (ulong)rowstride + (ulong)width * pixel_size)
                               ^
src/panel/widgets/notifications/notification-info.cpp:55:34: error: use of undeclared identifier 'ulong'
    if (data_var.get_size() != ((ulong)height - 1) * (ulong)rowstride + (ulong)width * pixel_size)
                                 ^
src/panel/widgets/notifications/notification-info.cpp:55:55: error: use of undeclared identifier 'ulong'
    if (data_var.get_size() != ((ulong)height - 1) * (ulong)rowstride + (ulong)width * pixel_size)
                                                      ^
src/panel/widgets/notifications/notification-info.cpp:55:61: error: expected ')'
    if (data_var.get_size() != ((ulong)height - 1) * (ulong)rowstride + (ulong)width * pixel_size)
                                                            ^
src/panel/widgets/notifications/notification-info.cpp:55:8: note: to match this '('
    if (data_var.get_size() != ((ulong)height - 1) * (ulong)rowstride + (ulong)width * pixel_size)
       ^

* command-output: add missing header for libc++ 14 after ff9f7913d097

src/panel/widgets/command-output.cpp:25:30: error: implicit instantiation of undefined template 'std::array<char, 16>'
        std::array<char, 16> buffer;
                             ^
/usr/include/c++/v1/__tuple:219:64: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
                                                               ^