command-output: add missing header for libc++ 14 after ff9f7913d097
src/panel/widgets/command-output.cpp:25:30: error: implicit instantiation of undefined template 'std::array<char, 16>'
        std::array<char, 16> buffer;
                             ^
/usr/include/c++/v1/__tuple:219:64: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
                                                               ^